kumuluzee:
  name: subjects
  version: 1.0.0
  server:
    base-url: http://192.168.99.100:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/Subjects
      connection-url: jdbc:postgresql://192.168.99.100:32772/subjects
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 30
    ping-interval: 5
