kumuluzee:
  name: users
  version: 1.0.0
  server:
    base-url: http://192.168.99.100:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/Users
      connection-url: jdbc:postgresql://192.168.99.100:5432/users
      username: postgres
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 30
    ping-interval: 5
